import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { ValidationPipe } from '@nestjs/common/pipes';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      transform: true,
      transformOptions: {
        enableImplicitConversion: true,
      },
    }),
  );
  const options = new DocumentBuilder()
    .setTitle('Realtor APIs')
    .setDescription(
      `Realtor Backend-API using Nestjs by struct.dev
    A User could either be a buyer, realtor or an admin, just for simplicity the api supports just 2 Property types, CONDO OR RESIDENTIAL, to be a Realtor a product key would be generated by an admin user then issued to the user`,
    )
    .setContact(
      'Muyiwa',
      'https://github.com/muyiwadosunmu/realtor-backend',
      'oluwamuyiwadosunmu@duck.com',
    )
    .setVersion('1.0')
    .build();
  const document = SwaggerModule.createDocument(app, options);
  //Code below wires up everything with route path, app instance and doc object
  SwaggerModule.setup('api', app, document);
  await app.listen(3000);
}
bootstrap();
